spring:
  cloud:
    gateway:
      routes:
        - id: command-service
          uri: lb://COMMAND-SERVICE
          predicates:
            - Path=/commands/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: security-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: APP-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
